---

- hosts: group1
  remote_user: ec2-user
  become: yes
  become_user: root

  tasks:
   - name: restart apache
     service:
         name: httpd
         debug: msg="Apache is started"
         when:
         state: started 
